// <auto-generated />
using System;
using AutoDegreeMap.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AutoDegreeMap.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AutoDegreeMap.Models.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Pass")
                        .HasColumnType("boolean");

                    b.Property<int?>("SemesterPlanId")
                        .HasColumnType("integer");

                    b.HasKey("CourseID");

                    b.HasIndex("DegreeId");

                    b.HasIndex("SemesterPlanId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AutoDegreeMap.Models.CourseInstance", b =>
                {
                    b.Property<string>("CourseInstanceID")
                        .HasColumnType("text");

                    b.Property<string>("CourseID")
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .HasColumnType("text");

                    b.Property<string>("Teacher")
                        .HasColumnType("text");

                    b.HasKey("CourseInstanceID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseInstances");
                });

            modelBuilder.Entity("AutoDegreeMap.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RequiredCredits")
                        .HasColumnType("integer");

                    b.HasKey("DegreeId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("AutoDegreeMap.Models.SemesterPlan", b =>
                {
                    b.Property<int>("SemesterPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("SemesterPlanId");

                    b.ToTable("SemesterPlans");
                });

            modelBuilder.Entity("AutoDegreeMap.Models.Course", b =>
                {
                    b.HasOne("AutoDegreeMap.Models.Degree", null)
                        .WithMany("RequiredCourses")
                        .HasForeignKey("DegreeId");

                    b.HasOne("AutoDegreeMap.Models.SemesterPlan", null)
                        .WithMany("Courses")
                        .HasForeignKey("SemesterPlanId");
                });

            modelBuilder.Entity("AutoDegreeMap.Models.CourseInstance", b =>
                {
                    b.HasOne("AutoDegreeMap.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");
                });
#pragma warning restore 612, 618
        }
    }
}
